services:
  libreria-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: libreria-service
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:h2:file:/data/libreria_db
      SPRING_H2_CONSOLE_ENABLED: "true"
    volumes:
      - h2_data:/data
    networks:
      - libreria_network

volumes:
  h2_data:

networks:
  libreria_network:
    driver: bridge